server:
  servlet:
    context-path: '/university/'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/university'
    username: 'natanius'
    password: '12345'
    driver-class-name: org.postgresql.Driver
  flyway:
    url: "jdbc:postgresql://localhost:5432/university"
    user: "natanius"
    password: "12345"
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: NON_NULL
  flyway.baseline-on-migrate: true
